name = "urban-dict"
main = "./main.ts"
compatibility_date = "2026-05-26"
workers_dev = true
preview_urls = true
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "mise build --tiny"
watch_dir = ["pkg", "main.go"]

[vars]
SERVICE_NAME = "urban-dict"

[observability.logs]
enabled = true

[[tail_consumers]]
service = "axiom-tail-worker"
