// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package pkg

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeUrbanDictPkg(in *jlexer.Lexer, out *UrbanDictRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "list":
			if in.IsNull() {
				in.Skip()
				out.List = nil
			} else {
				in.Delim('[')
				if out.List == nil {
					if !in.IsDelim(']') {
						out.List = make([]struct {
							Definition    string    `json:"definition"`
							Permalink     string    `json:"permalink"`
							ThumbsUp      int       `json:"thumbs_up"`
							Author        string    `json:"author"`
							Word          string    `json:"word"`
							Defid         int       `json:"defid"`
							CurrentVote   string    `json:"current_vote"`
							WrittenOn     time.Time `json:"written_on"`
							Example       string    `json:"example"`
							ThumbsDown    int       `json:"thumbs_down"`
							Score         int
							OriginalIndex int
						}, 0, 0)
					} else {
						out.List = []struct {
							Definition    string    `json:"definition"`
							Permalink     string    `json:"permalink"`
							ThumbsUp      int       `json:"thumbs_up"`
							Author        string    `json:"author"`
							Word          string    `json:"word"`
							Defid         int       `json:"defid"`
							CurrentVote   string    `json:"current_vote"`
							WrittenOn     time.Time `json:"written_on"`
							Example       string    `json:"example"`
							ThumbsDown    int       `json:"thumbs_down"`
							Score         int
							OriginalIndex int
						}{}
					}
				} else {
					out.List = (out.List)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						Definition    string    `json:"definition"`
						Permalink     string    `json:"permalink"`
						ThumbsUp      int       `json:"thumbs_up"`
						Author        string    `json:"author"`
						Word          string    `json:"word"`
						Defid         int       `json:"defid"`
						CurrentVote   string    `json:"current_vote"`
						WrittenOn     time.Time `json:"written_on"`
						Example       string    `json:"example"`
						ThumbsDown    int       `json:"thumbs_down"`
						Score         int
						OriginalIndex int
					}
					easyjson6601e8cdDecode(in, &v1)
					out.List = append(out.List, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeUrbanDictPkg(out *jwriter.Writer, in UrbanDictRes) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.List) != 0 {
		const prefix string = ",\"list\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.List {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson6601e8cdEncode(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UrbanDictRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeUrbanDictPkg(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UrbanDictRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeUrbanDictPkg(l, v)
}
func easyjson6601e8cdDecode(in *jlexer.Lexer, out *struct {
	Definition    string    `json:"definition"`
	Permalink     string    `json:"permalink"`
	ThumbsUp      int       `json:"thumbs_up"`
	Author        string    `json:"author"`
	Word          string    `json:"word"`
	Defid         int       `json:"defid"`
	CurrentVote   string    `json:"current_vote"`
	WrittenOn     time.Time `json:"written_on"`
	Example       string    `json:"example"`
	ThumbsDown    int       `json:"thumbs_down"`
	Score         int
	OriginalIndex int
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "definition":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Definition = string(in.String())
			}
		case "permalink":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Permalink = string(in.String())
			}
		case "thumbs_up":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThumbsUp = int(in.Int())
			}
		case "author":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Author = string(in.String())
			}
		case "word":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Word = string(in.String())
			}
		case "defid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Defid = int(in.Int())
			}
		case "current_vote":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentVote = string(in.String())
			}
		case "written_on":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.WrittenOn).UnmarshalJSON(data))
				}
			}
		case "example":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Example = string(in.String())
			}
		case "thumbs_down":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThumbsDown = int(in.Int())
			}
		case "Score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = int(in.Int())
			}
		case "OriginalIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OriginalIndex = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncode(out *jwriter.Writer, in struct {
	Definition    string    `json:"definition"`
	Permalink     string    `json:"permalink"`
	ThumbsUp      int       `json:"thumbs_up"`
	Author        string    `json:"author"`
	Word          string    `json:"word"`
	Defid         int       `json:"defid"`
	CurrentVote   string    `json:"current_vote"`
	WrittenOn     time.Time `json:"written_on"`
	Example       string    `json:"example"`
	ThumbsDown    int       `json:"thumbs_down"`
	Score         int
	OriginalIndex int
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Definition != "" {
		const prefix string = ",\"definition\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Definition))
	}
	if in.Permalink != "" {
		const prefix string = ",\"permalink\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Permalink))
	}
	if in.ThumbsUp != 0 {
		const prefix string = ",\"thumbs_up\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThumbsUp))
	}
	if in.Author != "" {
		const prefix string = ",\"author\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Author))
	}
	if in.Word != "" {
		const prefix string = ",\"word\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Word))
	}
	if in.Defid != 0 {
		const prefix string = ",\"defid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Defid))
	}
	if in.CurrentVote != "" {
		const prefix string = ",\"current_vote\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CurrentVote))
	}
	if true {
		const prefix string = ",\"written_on\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.WrittenOn).MarshalJSON())
	}
	if in.Example != "" {
		const prefix string = ",\"example\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Example))
	}
	if in.ThumbsDown != 0 {
		const prefix string = ",\"thumbs_down\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThumbsDown))
	}
	if in.Score != 0 {
		const prefix string = ",\"Score\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Score))
	}
	if in.OriginalIndex != 0 {
		const prefix string = ",\"OriginalIndex\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.OriginalIndex))
	}
	out.RawByte('}')
}
