// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package pkg

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeUrbanDictPkg(in *jlexer.Lexer, out *UrbanDictRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "list":
			if in.IsNull() {
				in.Skip()
				out.List = nil
			} else {
				in.Delim('[')
				if out.List == nil {
					if !in.IsDelim(']') {
						out.List = make([]ResultList, 0, 1)
					} else {
						out.List = []ResultList{}
					}
				} else {
					out.List = (out.List)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ResultList
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.List = append(out.List, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeUrbanDictPkg(out *jwriter.Writer, in UrbanDictRes) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.List) != 0 {
		const prefix string = ",\"list\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.List {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UrbanDictRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeUrbanDictPkg(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UrbanDictRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeUrbanDictPkg(l, v)
}
func easyjson6601e8cdDecodeUrbanDictPkg1(in *jlexer.Lexer, out *ResultList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "definition":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Definition = string(in.String())
			}
		case "thumbs_up":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThumbsUp = int(in.Int())
			}
		case "word":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Word = string(in.String())
			}
		case "thumbs_down":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThumbsDown = int(in.Int())
			}
		case "score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeUrbanDictPkg1(out *jwriter.Writer, in ResultList) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Definition != "" {
		const prefix string = ",\"definition\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Definition))
	}
	if in.ThumbsUp != 0 {
		const prefix string = ",\"thumbs_up\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThumbsUp))
	}
	if in.Word != "" {
		const prefix string = ",\"word\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Word))
	}
	if in.ThumbsDown != 0 {
		const prefix string = ",\"thumbs_down\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ThumbsDown))
	}
	if in.Score != 0 {
		const prefix string = ",\"score\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Score))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeUrbanDictPkg1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeUrbanDictPkg1(l, v)
}
